#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

        _       _     __ _                  
  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
 /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
/ /\/\ \ | | | | | / /__| | | | | |_| |>  < 
\/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\ 


Welcome to mini_linux


!

/sbin/ifconfig eth0 10.0.2.15 netmask 255.255.255.0
/sbin/route    add default gw 10.0.2.2
/bin/echo      "nameserver 8.8.8.8" > /etc/resolv.conf
exec /bin/sh